on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: testing
      run: |
        SBT_OPTS=something echo $SBT_OPTS
    
